# n-d Array

In [4]:
#1-D array
import numpy as np
a = np.array([1,2,3])
print(a)

[1 2 3]


In [5]:
#2-D array
import numpy as np
b=np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [6]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
b[0] #1st row

array([1, 2, 3])

In [9]:
b[1] #2nd row

array([4, 5, 6])

In [12]:
print(type(a))
print(type(b))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


# Initializing Numpy array

In [13]:
import numpy as np
np.zeros((3,4))
#np.zeros((row,column))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

Arranging the numbers between x and y with an interval

In [16]:
import numpy as np
#np.arange(1st value,last value, interval)
np.arange(10,25,5)

array([10, 15, 20])

In [17]:
import numpy as np
np.arange(10,30,3)

array([10, 13, 16, 19, 22, 25, 28])

In [18]:
import numpy as np
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

Arranging 'z' numbers between x and y

In [19]:
import numpy as np
np.linspace(5,10,5)

array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [20]:
import numpy as np
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [21]:
import numpy as np
np.linspace(0,10,6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

Filling same number in a array 

In [23]:
import numpy as np
#np.full((row,column),number)
np.full((3,4),5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [24]:
import numpy as np
#np.full((row,column),number)
np.full((2,4),6)

array([[6, 6, 6, 6],
       [6, 6, 6, 6]])

Filling random number in a array

In [26]:
import numpy as np
#np.random.random((row,column))
np.random.random((2,4))

array([[0.60153718, 0.19433819, 0.7755493 , 0.85413017],
       [0.26948368, 0.95984364, 0.8983447 , 0.46908905]])

In [27]:
import numpy as np
#np.random.random((row,column))
np.random.random((3,3))

array([[0.88845491, 0.5850806 , 0.8829867 ],
       [0.1716104 , 0.40295166, 0.18783322],
       [0.37670978, 0.19487409, 0.51075963]])

# Numpy array dimensions

In [28]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(a.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [29]:
import numpy as np
a=np.array([[1,2,3,5],[4,4,5,6],[6,7,8,9]])
print(a)
print(a.shape)

[[1 2 3 5]
 [4 4 5 6]
 [6 7 8 9]]
(3, 4)


In [30]:
a= np.array([[1,2,3],[4,5,6]])

In [32]:
print(a)
print(a.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [44]:
a.shape=(3,2)
print(a)
print(a[1]) #2nd row
print(a.shape[0]) #shows the row number 
print(a.shape[1]) #shows the column number 

[[1 2]
 [3 4]
 [5 6]]
[3 4]
3
2


Array arrange number

In [45]:
import numpy as np
a=np.arange(24)

print(a.size)
print(a)

24
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


Dimensions

In [51]:
a=np.array([[1,2,3],[4,5,6]])
a.shape=(3,2)
print(a)
#number of dimensions of the array
print(a.ndim)

[[1 2]
 [3 4]
 [5 6]]
2


Returns datatype of an array

In [62]:
import numpy as np
a= np.arange(24,dtype=float)
print(a)
print(a.size)
print(a.ndim)
print(a.dtype)

b=a.reshape(3,4,2)
print(b)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23.]
24
1
float64
[[[ 0.  1.]
  [ 2.  3.]
  [ 4.  5.]
  [ 6.  7.]]

 [[ 8.  9.]
  [10. 11.]
  [12. 13.]
  [14. 15.]]

 [[16. 17.]
  [18. 19.]
  [20. 21.]
  [22. 23.]]]


# Array Mathematics

In [64]:
import numpy as np
a,b=10,20
np.sum([a,b])

30

In [72]:
a=[5,10]
b=[2,3]

np.subtract(a,b)

array([3, 7])

In [70]:
a=np.array([[0,1],[0,5]])
print(a)

# axis =0 columnwise sum
b=np.sum(a,axis=0)
print(b)

# axis =1 rowwise sum
c=np.sum(a,axis=1)
print(c)


[[0 1]
 [0 5]]
[0 6]
[1 5]


In [74]:
a=[5,10]
b=[2,3]

print(a)
print(b)

[5, 10]
[2, 3]


In [75]:
np.divide(a,b)

array([2.5       , 3.33333333])

In [76]:
np.multiply(a,b)

array([10, 30])

In [77]:
np.exp(a)

array([  148.4131591 , 22026.46579481])

In [78]:
np.sqrt(b)

array([1.41421356, 1.73205081])

In [79]:
np.sin(a)

array([-0.95892427, -0.54402111])

In [80]:
np.cos(b)

array([-0.41614684, -0.9899925 ])

In [81]:
np.log(a)

array([1.60943791, 2.30258509])

Element-wise comparison

In [83]:
import numpy as np
a=[1,2,4]
b=[2,3,4]
c=[1,2,4]

print(np.equal(a,b))
print(np.equal(a,c))
print(np.equal(b,c))

[False False  True]
[ True  True  True]
[False False  True]


Array-wise comparison

In [84]:
import numpy as np
a=[1,2,4]
b=[2,3,4]
c=[1,2,4]

print(np.array_equal(a,b))
print(np.array_equal(a,c))
print(np.array_equal(b,c))

False
True
False


Aggregate Functions

In [86]:
import numpy as np
a=[1,2,4]
b=[2,3,4]
c=[1,2,4]

print(np.sum(a))
print(np.min(a))
print(np.mean(a))
print(np.median(a))
print(np.corrcoef(a))
print(np.std(a))

7
1
2.3333333333333335
2.0
1.0
1.247219128924647


# Numpy Array Broadcasting

In [87]:
import numpy as np

a= np.array([[0,0,0],[10,10,10],[20,20,20],[30,30,30]])
b=np.array([0,1,2])

print('First array:\n',a,'\n')
print('Second array:\n',b,'\n')
print('Broadcasting array:\n',a+b,'\n')

First array:
 [[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]] 

Second array:
 [0 1 2] 

Broadcasting array:
 [[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]] 



Indexing and Slicing in Numpy Array

In [9]:
# simple indexing
import numpy as np
a = np.array([11, 22, 33, 44, 55])

# index data
print(a)
print(a[0])
print(a[4])

[11 22 33 44 55]
11
55


In [13]:
# 2d indexing
import numpy as np
# define array
a = np.array([[11, 22], [33, 44], [55, 66]])
# index data
print(a)
print(a[0,0])
print(a[0,])
print(a[0,1])
print(a[2,0])

[[11 22]
 [33 44]
 [55 66]]
11
[11 22]
22
55


In [63]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print('Full array:\n',a,'\n')
print('Row Slicing:\n')
print('1st Row Slicing:\n',a[0])
print('2nd Row Slicing:\n',a[1])
print('3rd Row Slicing:\n',a[2],'\n')

print('1st Row Slicing in list:\n',a[:1],'\n')
print('1st Row all element Slicing in list:\n',a[:1,:],'\n')
print('1st Row 1st element Slicing in list:\n',a[:1,:1],'\n')
print('1st Row last two element Slicing in list:\n',a[:1,1:],'\n')

print('1st column Slicing in list:\n',a[:,:1],'\n')
print('2nd column Slicing in list:\n',a[:,1:2],'\n')
print('3rd column Slicing in list:\n',a[:,2:3],'\n')

#Here a[row:,:column]
print('2nd row- 2nd column middle element Slicing:\n',a[1:2,1:2],'\n')
print('3nd row- 3nd column last element Slicing:\n',a[2:3,2:3],'\n')

Full array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

Row Slicing:

1st Row Slicing:
 [1 2 3]
2nd Row Slicing:
 [4 5 6]
3rd Row Slicing:
 [7 8 9] 

1st Row Slicing in list:
 [[1 2 3]] 

1st Row all element Slicing in list:
 [[1 2 3]] 

1st Row 1st element Slicing in list:
 [[1]] 

1st Row last two element Slicing in list:
 [[2 3]] 

1st column Slicing in list:
 [[1]
 [4]
 [7]] 

2nd column Slicing in list:
 [[2]
 [5]
 [8]] 

3rd column Slicing in list:
 [[3]
 [6]
 [9]] 

2nd row- 2nd column middle element Slicing:
 [[5]] 

3nd row- 3nd column last element Slicing:
 [[9]] 



# Array Manipulation

Array Concatenation

In [65]:
import numpy as np
a=np.array([1,2,3])
b=np.array([3,4,5])

In [69]:
np.concatenate([a,b],axis=0)

array([1, 2, 3, 3, 4, 5])

In [82]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[3,4,5],[5,6,7]])

print('First array:\n',a,'\n')
print('Second array:\n',b,'\n')

print('row wise concate array:')
print(np.concatenate([a,b],axis=0),'\n')

print('column wise concate array:')
print(np.concatenate([a,b],axis=1),'\n')

First array:
 [[1 2 3]
 [4 5 6]] 

Second array:
 [[3 4 5]
 [5 6 7]] 

row wise concate array:
[[1 2 3]
 [4 5 6]
 [3 4 5]
 [5 6 7]] 

column wise concate array:
[[1 2 3 3 4 5]
 [4 5 6 5 6 7]] 



Array Stacking

In [99]:
import numpy as np
a=np.array([1,2,3])
b=np.array([3,4,5])
print('First array:',a)
print('Second array:',b,'\n')
print('Horizontal Stack:\n',np.hstack((a,b)),'\n')
print('Vertical Stack:\n',np.vstack((a,b)),'\n')

First array: [1 2 3]
Second array: [3 4 5] 

Horizontal Stack:
 [1 2 3 3 4 5] 

Vertical Stack:
 [[1 2 3]
 [3 4 5]] 



In [104]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[3,4,5],[5,6,7]])

print('First array:\n',a,'\n')
print('Second array:\n',b,'\n')

#Here Horizontal concate is equal to vertical stack
# vertical concate = horizontal stack = column stack 

print('Horizontal Stack:\n',np.hstack((a,b)),'\n')
print('Horizontal concate:')
print(np.concatenate([a,b],axis=0),'\n')

print('Vertical Stack:\n',np.vstack((a,b)),'\n')
print('Vertical concate:')
print(np.concatenate([a,b],axis=1),'\n')

print('Column Stack:')
print(np.column_stack((a,b)),'\n')


First array:
 [[1 2 3]
 [4 5 6]] 

Second array:
 [[3 4 5]
 [5 6 7]] 

Horizontal Stack:
 [[1 2 3 3 4 5]
 [4 5 6 5 6 7]] 

Horizontal concate:
[[1 2 3]
 [4 5 6]
 [3 4 5]
 [5 6 7]] 

Vertical Stack:
 [[1 2 3]
 [4 5 6]
 [3 4 5]
 [5 6 7]] 

Vertical concate:
[[1 2 3 3 4 5]
 [4 5 6 5 6 7]] 

Column Stack:
[[1 2 3 3 4 5]
 [4 5 6 5 6 7]] 



Splitting Arrays

In [116]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])

print(a,'\n')
print('Split 2 array in row:')
print(np.split(a,2,axis=0),'\n')

print('Split 3 array in column:')
print(np.split(a,3,axis=1))

[[1 2 3]
 [4 5 6]] 

Split 2 array in row:
[array([[1, 2, 3]]), array([[4, 5, 6]])] 

Split 3 array in column:
[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]


In [124]:
import numpy as np 
a = np.arange(9) 

print('First array:') 
print (a,'\n') 
  

print ('Split the array in 3 equal-sized subarrays:') 
b = np.split(a,3) 
print (b,'\n')  

print('Split the array at positions indicated in 1-D array:') 
b = np.split(a,[4,7])
print (b,'\n') 


print('Split the array at positions indicated in 1-D array:') 
c = np.split(a,[3,5,10])
print (c) 

First array:
[0 1 2 3 4 5 6 7 8] 

Split the array in 3 equal-sized subarrays:
[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])] 

Split the array at positions indicated in 1-D array:
[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8])] 

Split the array at positions indicated in 1-D array:
[array([0, 1, 2]), array([3, 4]), array([5, 6, 7, 8]), array([], dtype=int32)]


In [123]:
x = np.arange(8.0)
np.split(x, [3, 5, 6, 10])

[array([0., 1., 2.]),
 array([3., 4.]),
 array([5.]),
 array([6., 7.]),
 array([], dtype=float64)]